Repository theachoem/storypad, pull requests merged in 2025-06, with the labels that each got.

#399 Revert in app purchase for now
  android/app/src/main/AndroidManifest.xml
  ios/Runner.xcodeproj/project.pbxproj
  lib/initializers/revenue_cat_initializer.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: revert

#403 Close #402 require security to access archives or bins
  lib/views/archives/archives_view.dart
Labels: enhancement

#406 Improve community page
  assets/images/x_logo_500x500.png
  bin/dev
  bin/localization/data.csv
  lib/core/services/remote_config/remote_config_service.dart
  lib/core/services/url_opener_service.dart
  lib/core/storages/new_badge_storage.dart
  lib/gen/assets.gen.dart
  lib/views/community/community_content.dart
  lib/views/community/community_view.dart
  lib/views/community/local_widgets/community_card.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/end_drawer/community_tile.dart
  lib/views/home/local_widgets/end_drawer/home_end_drawer.dart
  lib/widgets/bottom_sheets/sp_share_app_bottom_sheet.dart
  lib/widgets/sp_icons.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#411 Close #412 allow resize & align image
  lib/views/stories/local_widgets/base_story_view_model.dart
  lib/widgets/asset_db/sp_db_image_provider.dart
  lib/widgets/custom_embed/sp_image_block_embed.dart
  lib/widgets/quill/custom_attributes/embed_alignment_attribute.dart
  lib/widgets/quill/custom_attributes/embed_size_attribute.dart
  lib/widgets/sp_floating_pop_up_button.dart
  lib/widgets/sp_icons.dart
Labels: enhancement

#413 Move some actions to sheet from story view to avoid too much actions for user
  bin/localization/data.csv
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/local_widgets/manage_pages_button.dart
  lib/views/stories/local_widgets/story_info_button.dart
  lib/views/stories/local_widgets/story_theme_button.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view.dart
  lib/widgets/bottom_sheets/sp_story_theme_bottom_sheet.dart
  lib/widgets/custom_embed/sp_image_block_embed.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#415 Close #414 allow export individual story as txt / markdown
  lib/core/services/quill/quill_root_to_plain_text_service.dart
  lib/core/services/story_plain_text_exporter.dart
  lib/widgets/bottom_sheets/sp_share_story_bottom_sheet.dart
  lib/widgets/bottom_sheets/sp_story_theme_bottom_sheet.dart
  test/core/services/quill/quill_root_to_plain_text_service_test.dart
Labels: enhancement

#418 Allow change font size
  bin/localization/data.csv
  lib/core/databases/models/story_preferences_db_model.dart
  lib/core/databases/models/story_preferences_db_model.g.dart
  lib/core/services/analytics/analytics_user_propery_service.dart
  lib/core/services/quill/quill_root_to_plain_text_service.dart
  lib/core/types/font_size_option.dart
  lib/views/theme/local_widgets/font_size_tile.dart
  lib/widgets/bottom_sheets/sp_font_size_sheet.dart
  lib/widgets/bottom_sheets/sp_story_theme_bottom_sheet.dart
  lib/widgets/sp_icons.dart
  lib/widgets/sp_story_preference_theme.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#425 Close #424 add throwback to previous years feature 🕰️
  bin/localization/data.csv
  lib/core/constants/feature_flags.dart
  lib/core/databases/adapters/objectbox/stories_box.dart
  lib/core/objects/search_filter_object.dart
  lib/views/home/home_content.dart
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/throwback_tile.dart
  lib/views/throwback/throwback_content.dart
  lib/views/throwback/throwback_view.dart
  lib/views/throwback/throwback_view_model.dart
  lib/widgets/sp_icons.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature
