Repository theachoem/storypad, pull requests merged in 2025-03, with the labels that each got.

#289 Close #288 add community page
  assets/images/reddit_logo_500x500.png
  bin/localization/data.csv
  lib/core/databases/models/story_db_model.g.dart
  lib/core/services/remote_config/remote_config_service.dart
  lib/gen/assets.gen.dart
  lib/views/community/community_content.dart
  lib/views/community/community_view.dart
  lib/views/community/community_view_model.dart
  lib/views/community/local_widgets/community_card.dart
  lib/views/home/home_view.dart
  lib/views/home/local_widgets/community_tile.dart
  lib/views/home/local_widgets/home_end_drawer.dart
  lib/views/home/local_widgets/language_tile.dart
  lib/views/home/local_widgets/more_options_button.dart
  pubspec.lock
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#291 Close #290 preload home data before rendering
  lib/core/databases/legacy/storypad_legacy_database.dart
  lib/initializers/home_initializer.dart
  lib/main.dart
  lib/providers/backup_provider.dart
  lib/routes/base_route.dart
  lib/views/archives/archives_view_model.dart
  lib/views/home/home_content.dart
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/home_app_bar_nickname.dart
  lib/widgets/sp_dot_lottie_builder.dart
  lib/widgets/story_list/story_list.dart
  lib/widgets/story_list/story_tile_actions.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#292 Close #268 improve user property & image analytics
  lib/core/services/analytics/analytics_service.dart
  lib/core/services/analytics/analytics_user_propery_service.dart
  lib/core/services/analytics/base_analytics_service.dart
  lib/core/services/image_picker_service.dart
  lib/core/services/url_opener_service.dart
  lib/providers/backup_provider.dart
  lib/providers/local_auth_provider.dart
  lib/providers/tags_provider.dart
  lib/providers/theme_provider.dart
  lib/routes/base_route.dart
  lib/views/backups/offline_backup/offline_backup_view_model.dart
  lib/views/community/community_view.dart
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/languages/languages_content.dart
  lib/views/languages/languages_view.dart
  lib/views/search/search_view_model.dart
  lib/views/stories/changes/story_changes_view_model.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/widgets/sp_images_viewer.dart
  lib/widgets/story_list/story_tile_actions.dart
Labels: enhancement

#294 Close #293 allow multi edit on homepage
  bin/localization/data.csv
  lib/core/databases/models/story_db_model.dart
  lib/views/archives/archives_content.dart
  lib/views/archives/archives_view.dart
  lib/views/archives/archives_view_model.dart
  lib/views/home/home_content.dart
  lib/views/home/home_view.dart
  lib/views/home/local_widgets/home_scaffold.dart
  lib/views/stories/changes/story_changes_content.dart
  lib/views/stories/changes/story_changes_view.dart
  lib/views/tags/edit/edit_tag_view.dart
  lib/views/tags/show/show_tag_content.dart
  lib/views/tags/show/show_tag_view.dart
  lib/views/tags/show/show_tag_view_model.dart
  lib/views/tags/tags_content.dart
  lib/widgets/sp_multi_edit_bottom_nav_bar.dart
  lib/widgets/story_list/story_list_multi_edit_wrapper.dart
  lib/widgets/story_list/story_tile.dart
  lib/widgets/story_list/story_tile_favorite_button.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#296 Close #295 fix could not find generate dart define xxconfig file
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  lib/views/home/local_widgets/home_end_drawer.dart
  pubspec.yaml
Labels: bug

#298 Close #297 allow pick time and pin on home
  lib/core/databases/models/story_db_model.dart
  lib/core/databases/models/story_preferences_db_model.dart
  lib/core/databases/models/story_preferences_db_model.g.dart
  lib/core/services/analytics/analytics_service.dart
  lib/core/services/date_format_service.dart
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/local_widgets/story_header.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/widgets/sp_story_labels.dart
  lib/widgets/story_list/story_tile_actions.dart
  lib/widgets/story_list/story_tile_contents.dart
  lib/widgets/story_list/story_tile_favorite_button.dart
Labels: enhancement, feature

#299 Close #285 screen lock
  bin/localization/data.csv
  lib/app.dart
  lib/core/objects/app_lock_object.dart
  lib/core/objects/app_lock_object.g.dart
  lib/core/services/analytics/analytics_service.dart
  lib/core/services/analytics/analytics_user_propery_service.dart
  lib/core/services/local_auth_service.dart
  lib/core/storages/app_lock_storage.dart
  lib/core/storages/local_auth_enabled_storage.dart
  lib/core/types/app_lock_question.dart
  lib/initializers/app_lock_initializer.dart
  lib/initializers/local_auth_initializer.dart
  lib/main.dart
  lib/provider_scope.dart
  lib/providers/app_lock_provider.dart
  lib/providers/backup_provider.dart
  lib/providers/local_auth_provider.dart
  lib/routes/base_route.dart
  lib/views/app_locks/app_locks_content.dart
  lib/views/app_locks/app_locks_view.dart
  lib/views/app_locks/app_locks_view_model.dart
  lib/views/app_locks/security_questions/enter/enter_security_question_content.dart
  lib/views/app_locks/security_questions/enter/enter_security_question_view.dart
  lib/views/app_locks/security_questions/enter/enter_security_question_view_model.dart
  lib/views/app_locks/security_questions/security_questions_content.dart
  lib/views/app_locks/security_questions/security_questions_view.dart
  lib/views/app_locks/security_questions/security_questions_view_model.dart
  lib/views/community/local_widgets/community_card.dart
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/home_end_drawer.dart
  lib/widgets/sp_app_lock_wrapper.dart
  lib/widgets/sp_card.dart
  lib/widgets/sp_nested_navigation.dart
  lib/widgets/sp_pin_unlock.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature

#306 Close #304 replace changes with just draft / latest content instead
  bin/build_runner
  bin/docs
  bin/localization/data.csv
  docs/_config.yml
  docs/changelogs.md
  docs/changelogs/2.6.0.md
  lib/core/databases/adapters/objectbox/entities.dart
  lib/core/databases/adapters/objectbox/helpers/stories_box_transformer.dart
  lib/core/databases/adapters/objectbox/stories_box.dart
  lib/core/databases/legacy/storypad_legacy_database.dart
  lib/core/databases/models/story_content_db_model.dart
  lib/core/databases/models/story_content_db_model.g.dart
  lib/core/databases/models/story_db_model.dart
  lib/core/databases/models/story_db_model.g.dart
  lib/core/services/analytics/analytics_service.dart
  lib/core/services/stories/story_changes_to_raw_service.dart
  lib/core/services/stories/story_content_builder_service.dart
  lib/core/services/stories/story_has_changed_service.dart
  lib/core/services/stories/story_has_data_written_service.dart
  lib/core/services/stories/story_raw_to_changes_servce.dart
  lib/core/services/stories/story_should_revert_change_service.dart
  lib/initializers/database_initializer.dart
  lib/objectbox-model.json
  lib/objectbox.g.dart
  lib/views/archives/archives_view_model.dart
  lib/views/stories/changes/show/show_change_content.dart
  lib/views/stories/changes/show/show_change_view.dart
  lib/views/stories/changes/story_changes_content.dart
  lib/views/stories/changes/story_changes_view.dart
  lib/views/stories/changes/story_changes_view_model.dart
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/local_widgets/story_header.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/widgets/sp_story_labels.dart
  lib/widgets/story_list/story_list.dart
  lib/widgets/story_list/story_tile.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#318 Close #317 improve body trimming when display on home
  lib/core/databases/models/story_content_db_model.dart
  lib/core/services/markdown_body_shortener_service.dart
  test/core/services/markdown_body_shortener_service_test.dart
Labels: enhancement

#320 Close #319 improve editor context menu
  lib/core/constants/app_constants.dart
  lib/core/helpers/quill_context_menu_helper.dart
  lib/core/services/native_look_up_text_service.dart
  lib/core/services/validator/helpers.dart
  lib/core/services/validator/validator.dart
  lib/initializers/constants_initializer.dart
  lib/initializers/device_info_initializer.dart
  lib/initializers/file_initializer.dart
  lib/initializers/package_info_initializer.dart
  lib/main.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/local_widgets/editor.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#322 Close #321 use monochrome color for dark / light seed
  lib/app_theme.dart
  lib/core/constants/app_constants.dart
Labels: enhancement

#324 Close #323 add filter button
  bin/localization/data.csv
  lib/core/constants/app_constants.dart
  lib/core/databases/adapters/objectbox/stories_box.dart
  lib/core/objects/search_filter_object.dart
  lib/core/objects/search_filter_object.g.dart
  lib/core/storages/search_filter_storage.dart
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/home_app_bar.dart
  lib/views/home/local_widgets/home_flexible_space_bar.dart
  lib/views/home/local_widgets/home_tab_bar.dart
  lib/views/home/local_widgets/home_years_view.dart
  lib/views/search/filter/local_widgets/bottom_nav.dart
  lib/views/search/filter/local_widgets/scrollable_choice_chips.dart
  lib/views/search/filter/search_filter_content.dart
  lib/views/search/filter/search_filter_view.dart
  lib/views/search/filter/search_filter_view_model.dart
  lib/views/search/search_view_model.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/tags/show/show_tag_view_model.dart
  lib/widgets/sp_animated_icon.dart
  lib/widgets/sp_single_state_widget.dart
  lib/widgets/story_list/story_tile_favorite_button.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature

#325 Add share app button
  bin/localization/data.csv
  lib/core/services/share_app_service.dart
  lib/views/community/community_content.dart
  lib/views/community/community_view.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature

#326 Allow mutli edit stories on search & tag page
  lib/views/search/search_content.dart
  lib/views/search/search_view.dart
  lib/views/search/search_view_model.dart
  lib/views/tags/show/show_tag_content.dart
  lib/views/tags/show/show_tag_view.dart
  lib/views/tags/show/show_tag_view_model.dart
Labels: enhancement

#329 Move body with end drawer to adapt to IOS user
  lib/views/home/home_view.dart
  lib/views/home/local_widgets/home_scaffold.dart
Labels: enhancement

#331 Close #330 add native text processing context menu
  lib/core/constants/app_constants.dart
  lib/core/helpers/quill_context_menu_helper.dart
  lib/core/services/native_look_up_text_service.dart
  lib/initializers/constants_initializer.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#334 Close #281 allow to customize individual story
  bin/localization/data.csv
  lib/app_theme.dart
  lib/core/databases/adapters/objectbox/helpers/stories_box_transformer.dart
  lib/core/databases/models/story_db_model.dart
  lib/core/databases/models/story_db_model.g.dart
  lib/core/databases/models/story_preferences_db_model.dart
  lib/core/databases/models/story_preferences_db_model.g.dart
  lib/core/objects/theme_object.dart
  lib/core/services/analytics/analytics_service.dart
  lib/core/storages/recently_selected_fonts_storage.dart
  lib/providers/theme_provider.dart
  lib/views/fonts/fonts_content.dart
  lib/views/fonts/fonts_view.dart
  lib/views/fonts/fonts_view_model.dart
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/local_widgets/story_header.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/views/theme/local_widgets/color_seed_tile.dart
  lib/views/theme/local_widgets/font_family_tile.dart
  lib/views/theme/local_widgets/font_weight_tile.dart
  lib/views/theme/local_widgets/theme_mode_tile.dart
  lib/views/theme/theme_content.dart
  lib/views/theme/theme_view.dart
  lib/widgets/bottom_sheets/base_bottom_sheet.dart
  lib/widgets/bottom_sheets/fonts_sheet.dart
  lib/widgets/bottom_sheets/story_theme_bottom_sheet.dart
  lib/widgets/feeling_picker/sp_feeling_button.dart
  lib/widgets/sp_card.dart
  lib/widgets/sp_story_labels.dart
  lib/widgets/sp_story_preference_theme.dart
  lib/widgets/story_list/story_tile_actions.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement, feature

#337 Close #303 add 30 dynamic hello message
  bin/localization/data.csv
  lib/core/services/welcome_message_service.dart
  lib/views/home/home_view.dart
  lib/views/home/local_widgets/home_app_bar_message.dart
  lib/views/stories/edit/edit_story_view.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#340 Close #339 show story count base on filtered year
  lib/views/search/filter/search_filter_view_model.dart
Labels: enhancement

#341 Remove tag end drawer & use tags view for tag selection instead
  bin/localization/data.csv
  lib/providers/tags_provider.dart
  lib/views/stories/local_widgets/tags_end_drawer.dart
  lib/views/tags/show/show_tag_view_model.dart
  lib/views/tags/tags_content.dart
  lib/views/tags/tags_view.dart
  lib/views/tags/tags_view_model.dart
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: enhancement

#342 Close #338 add per app language android
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/locales_config.xml
  bin/localization/build.dart
  lib/views/languages/languages_content.dart
  lib/views/languages/languages_view.dart
  lib/views/languages/languages_view_model.dart
Labels: enhancement

#344 Close #343 add home navigations
  lib/views/home/home_view.dart
  lib/views/home/local_widgets/home_scaffold.dart
  lib/views/home/local_widgets/home_timeline_side_bar.dart
Labels: design, experiment

#346 Close #345 add multi page support
  .vscode/dart.code-snippets
  bin/localization/data.csv
  lib/core/databases/adapters/objectbox/helpers/stories_box_transformer.dart
  lib/core/databases/adapters/objectbox/stories_box.dart
  lib/core/databases/legacy/storypad_legacy_database.dart
  lib/core/databases/models/story_content_db_model.dart
  lib/core/databases/models/story_content_db_model.g.dart
  lib/core/databases/models/story_db_model.dart
  lib/core/databases/models/story_page_db_model.dart
  lib/core/databases/models/story_page_db_model.g.dart
  lib/core/helpers/date_format_helper.dart
  lib/core/services/analytics/analytics_service.dart
  lib/core/services/stories/story_content_builder_service.dart
  lib/core/services/stories/story_content_pages_to_document_service.dart
  lib/core/services/stories/story_content_to_quill_controllers_service.dart
  lib/core/services/stories/story_extract_image_from_content_service.dart
  lib/core/services/stories/story_has_changed_service.dart
  lib/core/services/stories/story_has_data_written_service.dart
  lib/views/community/community_content.dart
  lib/views/home/local_widgets/end_drawer/community_tile.dart
  lib/views/stories/changes/show/show_change_content.dart
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/local_widgets/story_header.dart
  lib/views/stories/local_widgets/story_pages_managable.dart
  lib/views/stories/local_widgets/story_pages_manager.dart
  lib/views/stories/local_widgets/tags_end_drawer.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/widgets/custom_embed/sp_date_block_embed.dart
  lib/widgets/sp_card.dart
  lib/widgets/sp_floating_pop_up_button.dart
  lib/widgets/story_list/sp_story_tile.dart
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature

#347 Allow pages to be reorder / delete
  lib/core/mixins/list_reorderable.dart
  lib/core/services/stories/story_content_builder_service.dart
  lib/core/services/stories/story_content_to_quill_controllers_service.dart
  lib/core/services/stories/story_has_changed_service.dart
  lib/core/services/stories/story_has_data_written_service.dart
  lib/views/stories/changes/show/show_change_content.dart
  lib/views/stories/changes/show/show_change_view_model.dart
  lib/views/stories/edit/edit_story_content.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/views/stories/local_widgets/checked_icon.dart
  lib/views/stories/local_widgets/story_pages_bin_target.dart
  lib/views/stories/local_widgets/story_pages_managable.dart
  lib/views/stories/local_widgets/story_pages_manager.dart
  lib/views/stories/show/show_story_content.dart
  lib/views/stories/show/show_story_view.dart
  lib/views/stories/show/show_story_view_model.dart
  lib/views/tags/tags_content.dart
  lib/widgets/sp_reorderable_item.dart
  pubspec.yaml
Labels: enhancement

#349 add updated ko-KR translation
  bin/localization/data.csv
  translations/ko-KR.json
Labels: translation, community
