Repository theachoem/storypad, pull requests merged in 2025-04, with the labels that each got.

#354 Close #353 add button to open end drawer
  docs/index.html
  lib/views/home/home_view.dart
  lib/views/home/home_view_model.dart
  lib/views/home/local_widgets/home_flexible_space_bar.dart
  lib/views/home/local_widgets/home_tab_bar.dart
  pubspec.yaml
Labels: enhancement

#355 Add updated ja-JP translation
  bin/localization/data.csv
  translations/ja-JP.json
Labels: enhancement, community

#366 Close #284 bring back relax sound
  bin/localization/data.csv
  ios/Podfile.lock
  lib/core/services/audio_player_service.dart
  lib/core/services/multi_audio_player_service.dart
  lib/core/services/relax_sound_timer_service.dart
  lib/providers/relax_sounds_provider.dart
  lib/views/discover/discover_content.dart
  lib/views/discover/discover_view_model.dart
  lib/views/discover/segments/discover_relax_sounds_content.dart
  lib/views/discover/segments/discover_search_content.dart
  lib/views/discover/segments/local_widgets/sound_icon_card.dart
  lib/views/discover/segments/local_widgets/volume_slider.dart
  lib/widgets/bottom_sheets/sp_discover_sheet.dart
  lib/widgets/bottom_sheets/sp_fonts_sheet.dart
  lib/widgets/bottom_sheets/sp_image_picker_bottom_sheet.dart
  lib/widgets/sp_cache_file_downloader_builder.dart
  lib/widgets/sp_floating_relax_sound_tile.dart
  pubspec.lock
  pubspec.yaml
  translations/ar.json
  translations/de-DE.json
  translations/en.json
  translations/es-419.json
  translations/es-ES.json
  translations/fr-FR.json
  translations/hi-IN.json
  translations/id.json
  translations/it-IT.json
  translations/ja-JP.json
  translations/km.json
  translations/ko-KR.json
  translations/pl-PL.json
  translations/pt-BR.json
  translations/th.json
  translations/vi-VN.json
  translations/zh-CN.json
Labels: feature

#372 Close #278 calendar feature 📅
  lib/core/databases/adapters/objectbox/stories_box.dart
  lib/core/databases/models/story_db_model.dart
  lib/core/helpers/date_format_helper.dart
  lib/core/objects/search_filter_object.dart
  lib/core/services/calendar_days_generator.dart
  lib/core/services/days_count_in_month_service.dart
  lib/core/services/month_picker_service.dart
  lib/providers/backup_provider.dart
  lib/views/discover/discover_view_model.dart
  lib/views/discover/segments/discover_calendar_content.dart
  lib/views/discover/segments/local_widgets/calendar_date.dart
  lib/views/discover/segments/local_widgets/calendar_month.dart
  lib/views/discover/segments/local_widgets/calendar_month_header.dart
  lib/views/home/home_view.dart
  lib/views/stories/edit/edit_story_view.dart
  lib/views/stories/edit/edit_story_view_model.dart
  lib/widgets/feeling_picker/sp_feeling_button.dart
  lib/widgets/sp_icons.dart
  lib/widgets/story_list/local_widgets/story_tile_actions.dart
  lib/widgets/story_list/sp_story_list.dart
  lib/widgets/story_list/sp_story_list_multi_edit_wrapper.dart
  lib/widgets/story_list/sp_story_list_multi_edit_wrapper_state.dart
  lib/widgets/story_list/sp_story_tile.dart
  pubspec.yaml
  test/core/services/calendar_days_generator_test.dart
  test/core/services/days_count_in_month_service_test.dart
Labels: feature

#374 Close #371 cache relaxing sound progressively
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/core/services/audio_player_service.dart
Labels: enhancement

#376 Close #375 make home page easier to navigate
  lib/views/home/local_widgets/home_flexible_space_bar.dart
  lib/views/home/local_widgets/home_scaffold.dart
  lib/views/home/local_widgets/home_timeline_side_bar.dart
  lib/widgets/story_list/sp_story_tile.dart
Labels: enhancement
